valor = input('Digite algo: ').strip()
print('O tipo primitivo desse valor é', type(valor))
print('O valor só tem espaços?', valor.isspace())
print('O valor é alfabético?', valor.isalpha())
print('O valor é um número?', valor.isnumeric())
print('O valor possúi letras ou números?', valor.isalnum())
print('O valor está em letras maiusculas?', valor.isupper())
print('O valor está em letras minusculas?', valor.islower())
print('O valor está capitalizado?', valor.istitle())
print('O valor é flot?', valor.isdecimal())
