valor = int(input('Digite o número ao qual você quer saber a tabuada: '))
valor1 = valor * 1
valor2 = valor * 2
valor3 = valor * 3
valor4 = valor * 4
valor5 = valor * 5
valor6 = valor * 6
valor7 = valor * 7
valor8 = valor * 8
valor9 = valor * 9
valor10 = valor * 10
print(f'{valor}x1 = {valor1}')
print(f'{valor}x2 = {valor2}')
print(f'{valor}x3 = {valor3}')
print(f'{valor}x4 = {valor4}')
print(f'{valor}x5 = {valor5}')
print(f'{valor}x6 = {valor6}')
print(f'{valor}x7 = {valor7}')
print(f'{valor}x8 = {valor8}')
print(f'{valor}x9 = {valor9}')
print(f'{valor}x10 = {valor10}')
